# Generated by Django 3.1.2 on 2020-11-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('course_id', models.CharField(max_length=16, verbose_name='شناسه درس')),
                ('year', models.PositiveSmallIntegerField(verbose_name='سال ارائه\u200cشدن درس')),
                ('semester', models.CharField(choices=[('fall', 'ترم پاییز'), ('spring', 'ترم بهار'), ('summer', 'ترم تابستان')], max_length=8, verbose_name='ترم ارائه\u200cشدن درس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject', verbose_name='درس')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.lecturer', verbose_name='استاد درس')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.university', verbose_name='دانشکاه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(max_length=64, verbose_name='نام وظیفه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_procedures.course', verbose_name='درس ارائه شده')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subjects.student', verbose_name='دستیار آموزشی')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='roles/', verbose_name='فایل ضمیمه وظیفه')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ta_procedures.role', verbose_name='وظیقه')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
